#! /bin/bash
#引数としてコミットの ハッシュ HEAD HEAD^ 等のmergeコミットを一つ入力
#automergeが起きたファイルを全て表示

#入力されたコミットの親の数を確認
PearentNum=$(echo $(git log $1 -1 --pretty=format:"%P" | wc -w))

#merge commitかチェック
if [ $PearentNum -gt 1 ] ; then
	#親が2以上(merge commitの場合)
	#入力されたコミットとその親との差分が存在するファイル名からmergeが行われたファイルを列挙

	#マージが行われたファイル名一覧用変数の初期化
	MergedFiles=""

	#親の数だけループ
	i=1
	for Pearent in $(git log $1 -1 --pretty=format:"%P")
	do
		#一応親のハッシュを出力しておく
		echo "Pearent $i : $Pearent"
		MergedFiles=$(echo -e "$(git diff --name-only $1 $Pearent)\n${MergedFiles}")
		i=$(expr $i + 1)
	done

	#空行削除後、mergeされたファイル名をソートし、重複ファイルを抽出
	AutoMerged=$(echo "$MergedFiles" | grep -v "^$" | sort | uniq --repeated)
	
	#重複しているファイルがあれば出力
	if [ -n "$AutoMerged" ] ; then
		echo " *AutoMerged filenames..."
		echo "$AutoMerged"
	else
		echo "no automerge"
	fi

else
	#親が2以上いないなら処理を終了
	echo "$(git log $1 -1 --pretty=format:"%P") is not MergeCommit"
fi

